### ISSUE TITLE
Deployed version is outdated

### ISSUE THREAD

**Issue by dpgil** [avadavat/truth-fiddle#20]
Commit c0fdcaedbb59dcd1e4b4775b2d7de7f8e15fed5d isn't in production

**Comment by jbadlato** [comment]
This was because of differing npm versions causing untracked changes in `package-lock.json` on the server, causing `git pull` to fail.

We shouldn't be using `git pull` for this reason.  Cleaned up deployment process with a new deployment script using `git fetch` instead with d57d798fca89bc37e3467d120865951be1466822
