### ISSUE TITLE
Unexpected behavior for some invalid expressions

### ISSUE THREAD

**Issue by jbadlato** [avadavat/truth-fiddle#22]
Reproduce by inputting: `p andq`

p | andq | Result
-- | -- | --
false | false | false
false | true | false
true | false | undefined
true | true | undefined

**Comment by jbadlato** [comment]
Sounds related to #8, but different enough that it should be tracked separately

**Comment by dpgil** [comment]
I don't see undefined anymore I think because of one of your commits today with the logic `row.value ? 'T' : 'F'` so undefined will display false. 

 Looks like the grammar is pulling the `and` out and then treating q as the second variable. This makes sense that the grammar doesn't expect spaces because otherwise `(p and q)` would treat `(p` as a variable and `q)` as the other. I think this can be solved by adding spaces around the special keywords in the grammar

**Comment by dpgil** [comment]
Fixed with c7d40d34ac07a183cf47530ad7a2ae7e657f1b74

Only change now is you can't do `not(p and q)` it has to be `not (p and q)`. We can work on more improvements later but I think this is a good change
